# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField()),
                ('salesperson', models.TextField()),
                ('owner_email', models.TextField()),
                ('company_name', models.TextField()),
                ('company_natural', models.TextField()),
                ('company_website', models.TextField()),
                ('company_details', models.TextField()),
                ('full_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('country', models.TextField()),
                ('phone', models.TextField()),
                ('company_linkedin', models.TextField()),
                ('company_industry', models.TextField()),
                ('number_of_employees', models.TextField()),
                ('revenue_in_millions_in_usd', models.TextField()),
                ('company_region', models.TextField()),
            ],
        ),
    ]
