# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210325_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_industry',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_linkedin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_natural',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_website',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='external_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_employees',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='revenue_in_millions_in_usd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='salesperson',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='zipcode',
            field=models.TextField(null=True),
        ),
    ]
